sources:
- platform: instagram
  priority: high
  type: creator
  value: alphachanneling
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: regards_coupables
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: cecile_hoodie
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: fromjordyn
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: eroticwatercolor
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: carlyjeanandrews
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: tinamariaelena
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: elenareyesstudio
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: bonercandy69
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: flupieland
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: victongai
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: estine.coquerelle
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: melodieperrault
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: eromaticax
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: lepetitvoyeur
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: dvrkshines
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: kliuwong
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: fridacastelli
  niche: art-erotica
- platform: instagram
  priority: high
  type: creator
  value: Petite_Boheme
  niche: art-erotica

creators:
  art-erotica:
    - alphachanneling
    - regards_coupables
    - cecile_hoodie
    - fromjordyn
    - eroticwatercolor
    - carlyjeanandrews
    - tinamariaelena
    - elenareyesstudio
    - bonercandy69
    - flupieland
    - victongai
    - estine.coquerelle
    - melodieperrault
    - eromaticax
    - lepetitvoyeur
    - dvrkshines
    - kliuwong
    - fridacastelli
    - Petite_Boheme

global_filters:
  instagram:
    media_type: reels
    min_likes: 1000
    min_views: 10000
