discovered_creators:
- followers: 4000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214425'
  platform: instagram
  type: creator
  value: chrisburkard
- followers: 3000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214438'
  platform: instagram
  type: creator
  value: wibmerfabio
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214441'
  platform: instagram
  type: creator
  value: danielkordan
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214443'
  platform: instagram
  type: creator
  value: passionpassport
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214445'
  platform: instagram
  type: creator
  value: alexstrohl
- followers: 3000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214447'
  platform: instagram
  type: creator
  value: kellyslater
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214448'
  platform: instagram
  type: creator
  value: helloemilie
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214450'
  platform: instagram
  type: creator
  value: yukamedya
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214452'
  platform: instagram
  type: creator
  value: wanderwithsky
- followers: 46000000
  importance: high
  last_checked: '2026-03-19T13:42:39.214454'
  platform: instagram
  type: creator
  value: natgeotravel
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214455'
  platform: instagram
  type: creator
  value: bruisedpassports
- followers: 3000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214457'
  platform: instagram
  type: creator
  value: jimmychin
- followers: 3000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214459'
  platform: instagram
  type: creator
  value: bethanyhamilton
- followers: 3000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214461'
  platform: instagram
  type: creator
  value: thebucketlistfamily
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214463'
  platform: instagram
  type: creator
  value: shecks
- followers: 3000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214464'
  platform: instagram
  type: creator
  value: sarah
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214466'
  platform: instagram
  type: creator
  value: jackmorris
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214468'
  platform: instagram
  type: creator
  value: brindasharma
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214470'
  platform: instagram
  type: creator
  value: nimsdai
- followers: 3000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214471'
  platform: instagram
  type: creator
  value: izkiz
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214473'
  platform: instagram
  type: creator
  value: angelicablick
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214475'
  platform: instagram
  type: creator
  value: ryanresatka
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214476'
  platform: instagram
  type: creator
  value: candidethovex
- followers: 3000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214478'
  platform: instagram
  type: creator
  value: muradosmann
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214480'
  platform: instagram
  type: creator
  value: matteopelusi
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214482'
  platform: instagram
  type: creator
  value: lexielimitless
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214483'
  platform: instagram
  type: creator
  value: kyrenian
- followers: 2000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214485'
  platform: instagram
  type: creator
  value: gypsea_lust
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214487'
  platform: instagram
  type: creator
  value: drewbinsky
- followers: 1000000
  importance: normal
  last_checked: '2026-03-19T13:42:39.214488'
  platform: instagram
  type: creator
  value: anunaysood
