sources:
- platform: instagram
  priority: high
  type: creator
  value: iamsiddhi_1
  niche: hot-content
- platform: instagram
  priority: high
  type: creator
  value: iamjessika2
  niche: hot-content
- platform: instagram
  priority: high
  type: creator
  value: strictly.for.adults
  niche: hot-content
- platform: instagram
  priority: high
  type: creator
  value: nakedinmotion
  niche: hot-content
- platform: instagram
  priority: high
  type: creator
  value: kemeticyogi
  niche: hot-content
- platform: instagram
  priority: high
  type: creator
  value: getnakedaustralia
  niche: hot-content
- platform: instagram
  priority: high
  type: creator
  value: n_wanderings
  niche: hot-content
- platform: instagram
  priority: high
  type: creator
  value: freeyourbuns
  niche: hot-content
- platform: instagram
  priority: high
  type: creator
  value: vritomartis
  niche: hot-content
global_filters:
  instagram:
    media_type: reels
    min_likes: 1000
    min_views: 10000
