sources:
- platform: instagram
  priority: high
  type: creator
  value: jannatzubair29
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: arishfakhan138
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: iam_nishaguragain
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: nagmamirajkar
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: dianapenty
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: iam_ejf
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: mrunu
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: divyaagarwal_official
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: nehamalik335
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: rits_badiani
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: vishwa_rathod
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: barkhasingh0308
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: ritabhari_chakraborty
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: sanasultankhan
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: urf7i
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: rheakapoor
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: anitadongre
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: masabagupta
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: monami_ghosh
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: khushalikumar
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: taniazworld
  niche: indian-models
- platform: instagram
  priority: high
  type: creator
  value: komalpandeyofficial
  niche: indian-models
creators:
  indian-models:
  - jannatzubair29
  - arishfakhan138
  - iam_nishaguragain
  - nagmamirajkar
  - dianapenty
  - iam_ejf
  - mrunu
  - divyaagarwal_official
  - nehamalik335
  - rits_badiani
  - vishwa_rathod
  - barkhasingh0308
  - ritabhari_chakraborty
  - sanasultankhan
  - urf7i
  - rheakapoor
  - anitadongre
  - masabagupta
  - monami_ghosh
  - khushalikumar
  - taniazworld
  - komalpandeyofficial
global_filters:
  instagram:
    media_type: reels
    min_likes: 0
    min_views: 10
