sources:
- platform: instagram
  priority: high
  type: creator
  value: alphachanneling
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: antibart
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: bonercandy69
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: boundleatherzine
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: carlyjeanandrews
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: cecile_hoodie
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: daemonumx
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: eromaticax
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: estine.coquerelle
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: eva_oh
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: flupieland
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: fromjordyn
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: lovvr
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: mariussperlich
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: melodieperrault
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: nonothinginc
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: regards_coupables
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: rubberdei
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: thatcainguy
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: thelondonvagabond
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: tinamariaelena
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: vextape
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: victongai
  niche: kink-fetish-erotica
- platform: instagram
  priority: high
  type: creator
  value: youwillplease_me
  niche: kink-fetish-erotica
creators:
  kink-fetish-erotica:
  - alphachanneling
  - antibart
  - bonercandy69
  - boundleatherzine
  - carlyjeanandrews
  - cecile_hoodie
  - daemonumx
  - eromaticax
  - estine.coquerelle
  - eva_oh
  - flupieland
  - fromjordyn
  - lovvr
  - mariussperlich
  - melodieperrault
  - nonothinginc
  - regards_coupables
  - rubberdei
  - thatcainguy
  - thelondonvagabond
  - tinamariaelena
  - vextape
  - victongai
  - youwillplease_me
global_filters:
  instagram:
    media_type: reels
    min_likes: 0
    min_views: 10
